// <auto-generated />
using System;
using DigiTekShop.Identity.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigiTekShop.Identity.Migrations
{
    [DbContext(typeof(DigiTekShopIdentityDbContext))]
    partial class DigiTekShopIdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigiTekShop.Identity.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("User");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsSuccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NewValueJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValueJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Severity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("TargetEntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TargetEntityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("IX_AuditLogs_ActorId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditLogs_CorrelationId")
                        .HasFilter("[CorrelationId] IS NOT NULL");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Timestamp");

                    b.HasIndex("Action", "Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Action_Timestamp");

                    b.HasIndex("ActorId", "Timestamp")
                        .HasDatabaseName("IX_AuditLogs_ActorId_Timestamp");

                    b.HasIndex("Severity", "Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Severity_Timestamp");

                    b.HasIndex("TargetEntityName", "TargetEntityId", "Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Target_Timestamp");

                    b.HasIndex("TargetEntityName", "TargetEntityId", "Action", "Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Target_Action_Time");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.IdentityOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MessageKey")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTimeOffset?>("NextRetryUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_Outbox_CorrelationId")
                        .HasFilter("[CorrelationId] IS NOT NULL");

                    b.HasIndex("LockedUntilUtc")
                        .HasDatabaseName("IX_Outbox_LockedUntilUtc")
                        .HasFilter("[LockedUntilUtc] IS NOT NULL");

                    b.HasIndex("MessageKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Outbox_MessageKey")
                        .HasFilter("[MessageKey] IS NOT NULL");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_Outbox_OccurredAtUtc");

                    b.HasIndex("Status", "OccurredAtUtc")
                        .HasDatabaseName("IX_Outbox_Status_OccurredAtUtc");

                    b.HasIndex("Status", "NextRetryUtc", "OccurredAtUtc")
                        .HasDatabaseName("IX_Outbox_Status_NextRetry_OccurredAt");

                    b.ToTable("IdentityOutboxMessages", null, t =>
                        {
                            t.HasCheckConstraint("CK_Outbox_Attempts_NonNegative", "[Attempts] >= 0");
                        });
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.LoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("LoginNameOrEmail")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("LoginNameOrEmailNormalized")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt")
                        .HasDatabaseName("IX_LoginAttempts_AttemptedAt");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_LoginAttempts_CorrelationId")
                        .HasFilter("[CorrelationId] IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_LoginAttempts_UserId");

                    b.HasIndex("IpAddress", "AttemptedAt")
                        .HasDatabaseName("IX_LoginAttempts_Ip_Fail_Time")
                        .HasFilter("[IpAddress] IS NOT NULL AND [Status] <> 1");

                    b.HasIndex("LoginNameOrEmailNormalized", "AttemptedAt")
                        .HasDatabaseName("IX_LoginAttempts_LoginNorm_Fail_Time")
                        .HasFilter("[LoginNameOrEmailNormalized] IS NOT NULL AND [Status] <> 1");

                    b.HasIndex("Status", "AttemptedAt")
                        .HasDatabaseName("IX_LoginAttempts_Status_Time");

                    b.HasIndex("UserId", "AttemptedAt")
                        .HasDatabaseName("IX_LoginAttempts_UserId_Time");

                    b.HasIndex("IpAddress", "Status", "AttemptedAt")
                        .HasDatabaseName("IX_LoginAttempts_Ip_Status_Time");

                    b.HasIndex("LoginNameOrEmailNormalized", "Status", "AttemptedAt")
                        .HasDatabaseName("IX_LoginAttempts_Login_Status_Time")
                        .HasFilter("[LoginNameOrEmailNormalized] IS NOT NULL");

                    b.ToTable("LoginAttempts", (string)null);
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Permissions_CreatedAt");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Permissions_IsActive");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Permissions_Name");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.PhoneVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<byte>("Channel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CodeHashAlgo")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EncryptedCodeProtected")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PhoneNumberNormalized")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<byte>("Purpose")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SecretVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_PhoneVerifications_CreatedAt");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_PhoneVerifications_ExpiresAt");

                    b.HasIndex("LockedUntilUtc")
                        .HasDatabaseName("IX_PhoneVerifications_LockedUntil")
                        .HasFilter("[LockedUntilUtc] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("IX_PhoneVerifications_Phone");

                    b.HasIndex("PhoneNumberNormalized")
                        .HasDatabaseName("IX_PhoneVerifications_PhoneNormalized")
                        .HasFilter("[PhoneNumberNormalized] IS NOT NULL");

                    b.HasIndex("PhoneNumberNormalized", "IsVerified", "ExpiresAtUtc")
                        .HasDatabaseName("IX_PV_PhoneNormalized_Active");

                    b.HasIndex("PhoneNumberNormalized", "Purpose", "Channel")
                        .IsUnique()
                        .HasDatabaseName("UX_PV_Active_Phone_Purpose_Channel")
                        .HasFilter("[PhoneNumberNormalized] IS NOT NULL AND [IsVerified] = 0");

                    b.HasIndex("Purpose", "Channel", "ExpiresAtUtc")
                        .HasDatabaseName("IX_PV_Purpose_Channel_ExpiresAt");

                    b.HasIndex("UserId", "IsVerified", "ExpiresAtUtc")
                        .HasDatabaseName("IX_PV_User_Active");

                    b.ToTable("PhoneVerifications", (string)null);
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ParentTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("RotatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_RefreshTokens_CreatedAtUtc");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_RefreshTokens_ExpiresAtUtc");

                    b.HasIndex("ParentTokenId")
                        .HasDatabaseName("IX_RefreshTokens_ParentTokenId")
                        .HasFilter("[ParentTokenId] IS NOT NULL");

                    b.HasIndex("ReplacedByTokenId")
                        .HasDatabaseName("IX_RefreshTokens_ReplacedByTokenId")
                        .HasFilter("[ReplacedByTokenId] IS NOT NULL");

                    b.HasIndex("RevokedAtUtc")
                        .HasDatabaseName("IX_RefreshTokens_RevokedAtUtc");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_TokenHash");

                    b.HasIndex("UserId", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("UX_RefreshTokens_User_Device_Active")
                        .HasFilter("[RevokedAtUtc] IS NULL AND [DeviceId] IS NOT NULL");

                    b.HasIndex("UserId", "ExpiresAtUtc", "RevokedAtUtc")
                        .HasDatabaseName("IX_RefreshTokens_User_Active")
                        .HasFilter("[RevokedAtUtc] IS NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("UserId", "ExpiresAtUtc", "RevokedAtUtc"), new[] { "Id", "TokenHash", "DeviceId", "CreatedAtUtc" });

                    b.HasIndex("UserId", "DeviceId", "ExpiresAtUtc", "RevokedAtUtc")
                        .HasDatabaseName("IX_RefreshTokens_User_Device_Active")
                        .HasFilter("[RevokedAtUtc] IS NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("UserId", "DeviceId", "ExpiresAtUtc", "RevokedAtUtc"), new[] { "Id", "TokenHash", "CreatedAtUtc" });

                    b.ToTable("RefreshTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_RefreshTokens_ExpiresAfterCreated", "[ExpiresAtUtc] > [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_RefreshTokens_LastUsedRange", "([LastUsedAtUtc] IS NULL OR ([LastUsedAtUtc] >= [CreatedAtUtc] AND [LastUsedAtUtc] <= [ExpiresAtUtc]))");

                            t.HasCheckConstraint("CK_RefreshTokens_RevokedAfterCreated", "([RevokedAtUtc] IS NULL OR [RevokedAtUtc] >= [CreatedAtUtc])");

                            t.HasCheckConstraint("CK_RefreshTokens_RevokedConsistency", "(([RevokedAtUtc] IS NULL AND [RevokedReason] IS NULL) OR ([RevokedAtUtc] IS NOT NULL))");

                            t.HasCheckConstraint("CK_RefreshTokens_RotationConsistency", "(([RotatedAtUtc] IS NULL AND [ReplacedByTokenId] IS NULL) OR ([RotatedAtUtc] IS NOT NULL AND [ReplacedByTokenId] IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDefaultForNewUsers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Roles_CreatedAt");

                    b.HasIndex("IsDefaultForNewUsers")
                        .HasDatabaseName("IX_Roles_IsDefaultForNewUsers");

                    b.HasIndex("IsSystemRole")
                        .HasDatabaseName("IX_Roles_IsSystemRole");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_RolePermissions_CreatedAt");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("IX_RolePermissions_PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.SecurityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuditLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Severity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuditLogId")
                        .HasDatabaseName("IX_SecurityEvents_AuditLogId")
                        .HasFilter("[AuditLogId] IS NOT NULL");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_SecurityEvents_CorrelationId")
                        .HasFilter("[CorrelationId] IS NOT NULL");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_SecurityEvents_OccurredAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_SecurityEvents_UserId");

                    b.HasIndex("IsResolved", "OccurredAt")
                        .HasDatabaseName("IX_SecurityEvents_Unresolved_OccurredAt")
                        .HasFilter("[IsResolved] = 0");

                    b.HasIndex("Type", "IsResolved", "OccurredAt")
                        .HasDatabaseName("IX_SecurityEvents_Type_Resolved_OccurredAt");

                    b.HasIndex("UserId", "Type", "OccurredAt")
                        .HasDatabaseName("IX_SecurityEvents_UserId_Type_OccurredAt");

                    b.ToTable("SecurityEvents", (string)null);
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedPhoneNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TermsAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Users_Email_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NormalizedPhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_NormalizedPhone_Active")
                        .HasFilter("[IsDeleted] = 0 AND [NormalizedPhoneNumber] IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("IX_Users_Phone_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrowserInfo")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("DeviceFingerprint")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastIp")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TrustCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("TrustedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("TrustedUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenUtc")
                        .HasDatabaseName("IX_UserDevices_LastSeenUtc");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserDevices_UserId");

                    b.HasIndex("UserId", "DeviceFingerprint")
                        .IsUnique()
                        .HasDatabaseName("UX_UserDevices_User_Fingerprint")
                        .HasFilter("[DeviceFingerprint] IS NOT NULL");

                    b.HasIndex("UserId", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("UX_UserDevices_User_DeviceId");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("IX_UserDevices_User_IsActive");

                    b.HasIndex("UserId", "TrustedUntilUtc")
                        .HasDatabaseName("IX_UserDevices_User_TrustedUntil")
                        .HasFilter("[TrustedUntilUtc] IS NOT NULL");

                    b.HasIndex("UserId", "IsActive", "LastSeenUtc")
                        .HasDatabaseName("IX_UserDevices_User_Active_LastSeen");

                    b.ToTable("UserDevices", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserDevices_LastSeen_GTE_FirstSeen", "[LastSeenUtc] >= [FirstSeenUtc]");

                            t.HasCheckConstraint("CK_UserDevices_TrustRange", "([TrustedUntilUtc] IS NULL AND [TrustedAtUtc] IS NULL) OR ([TrustedUntilUtc] >= [TrustedAtUtc])");
                        });
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.UserMfa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastVerifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SecretKeyEncrypted")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("IX_UserMfa_IsEnabled");

                    b.HasIndex("IsLocked")
                        .HasDatabaseName("IX_UserMfa_IsLocked");

                    b.HasIndex("LastVerifiedAt")
                        .HasDatabaseName("IX_UserMfa_LastVerifiedAt")
                        .HasFilter("[LastVerifiedAt] IS NOT NULL");

                    b.HasIndex("LockedUntil")
                        .HasDatabaseName("IX_UserMfa_LockedUntil")
                        .HasFilter("[LockedUntil] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_UserMfa_UserId");

                    b.HasIndex("UserId", "IsEnabled", "IsLocked")
                        .HasDatabaseName("IX_UserMfa_User_Enabled_Locked");

                    b.ToTable("UserMfa", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserMfa_Attempts_NonNegative", "[Attempts] >= 0");

                            t.HasCheckConstraint("CK_UserMfa_LockRange", "([LockedUntil] IS NULL AND [LockedAt] IS NULL) OR ([LockedUntil] >= [LockedAt])");
                        });
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.UserPermission", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsGranted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_UserPermissions_CreatedAt");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("IX_UserPermissions_PermissionId");

                    b.HasIndex("UserId", "IsGranted")
                        .HasDatabaseName("IX_UserPermissions_User_Granted");

                    b.ToTable("UserPermissions", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserPermissions_Updated_GTE_Created", "([UpdatedAt] IS NULL OR [UpdatedAt] >= [CreatedAt])");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.PhoneVerification", b =>
                {
                    b.HasOne("DigiTekShop.Identity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.RefreshToken", b =>
                {
                    b.HasOne("DigiTekShop.Identity.Models.RefreshToken", "ParentToken")
                        .WithMany()
                        .HasForeignKey("ParentTokenId");

                    b.HasOne("DigiTekShop.Identity.Models.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DigiTekShop.Identity.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentToken");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.RolePermission", b =>
                {
                    b.HasOne("DigiTekShop.Identity.Models.Permission", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigiTekShop.Identity.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.UserDevice", b =>
                {
                    b.HasOne("DigiTekShop.Identity.Models.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.UserMfa", b =>
                {
                    b.HasOne("DigiTekShop.Identity.Models.User", "User")
                        .WithOne("Mfa")
                        .HasForeignKey("DigiTekShop.Identity.Models.UserMfa", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.UserPermission", b =>
                {
                    b.HasOne("DigiTekShop.Identity.Models.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigiTekShop.Identity.Models.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("DigiTekShop.Identity.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DigiTekShop.Identity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DigiTekShop.Identity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("DigiTekShop.Identity.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigiTekShop.Identity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DigiTekShop.Identity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.Permission", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("DigiTekShop.Identity.Models.User", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Mfa");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
