global using DigiTekShop.MVC.Models.Auth;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.DataProtection;
global using Microsoft.AspNetCore.HttpOverrides;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.ResponseCompression;
global using System.IdentityModel.Tokens.Jwt;
global using Yarp.ReverseProxy.Configuration;
global using Yarp.ReverseProxy.Transforms;
