global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity;
global using DigiTekShop.Identity.Models;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using DigiTekShop.Identity.Configurations;
global using DigiTekShop.Identity.Context;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using DigiTekShop.SharedKernel.Exceptions.Common;
global using DigiTekShop.Identity.Enums;
global using DigiTekShop.SharedKernel.Guards;
global using DigiTekShop.Identity.Exceptions.PhoneVerification;

